version: '3.3'
services:
  nginx:
    # deploy:
    #     resources:
    #         limits:
    #             cpus: '0.5'
    #             memory: 512M 
    container_name: nginx_PortalSPBE
    image: nginx:alpine
    ports:
      - 80:80
    depends_on : 
      - app
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always 
  app:
    container_name: portal_PortalSPBE
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    # ports:
    #   - "9001:9001"
    working_dir: /var/www/html
    restart: always 
  php:
    container_name: php_PortalSPBE
    image: php:8.2-fpm-alpine
    depends_on : 
      - app
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always 
      
  # bash:
  #   image: alpine:3.12
  #   volumes:
  #     - ./src:/var/www/html
  #   command: /bin/bash
  
  # composer:
  #   image: composer:2.0
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  
