version: "3.8"
services:
  services:
  app:
    build:
      args:
        user: zaki
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: portal-spbe
    container_name: portal-spbe
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ppaw

  db:
    image: mysql:5.7
    container_name: portal-spbe
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: portal-spbe
      MYSQL_ROOT_PASSWORD: rootspbe
      MYSQL_PASSWORD: password-spbe
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ppaw

  nginx:
    image: nginx:alpine
    container_name: portal-layanan-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ppaw

networks:
  ppaw:
    driver: bridge